#include<stdio.h>
#include<string.h>
#define N 80
int main()
{
	int a;
	char str1[N]="thank ";
	char str2[N]="you";
	char str3[N]=" ";
	strcat(str3,str1);
	printf("%s\n",str3);
	a=strcmp(str1,str2);
	printf("%d\n",a);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    strcpy(str3,str2);
	printf("%s",str3);
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     