server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.example.model
  config-location: classpath:mapper/*.xml

