// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.qin_kai.grpc.protobuf;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
