package com.example.model;

import java.io.Serializable;

/**
 * @TableName user
 */
public class User implements Serializable {
    /**
     * 自增id
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private Integer userId;

    /**
     * 用户名
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private String username;

    /**
     * 密码
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private String password;

    /**
     * 性别
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private Byte gender;

    /**
     * 角色
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private Byte role;

    /**
     * 用户头像
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private String avatar;

    /**
     * 用户昵称
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private String nickname;

    /**
     * 用户状态,0正常,1被踢出
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * 自增id
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 自增id
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 用户名
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * 用户名
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * 密码
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * 密码
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 性别
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * 性别
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * 角色
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public Byte getRole() {
        return role;
    }

    /**
     * 角色
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public void setRole(Byte role) {
        this.role = role;
    }

    /**
     * 用户头像
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * 用户头像
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * 用户昵称
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * 用户昵称
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * 用户状态,0正常,1被踢出
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 用户状态,0正常,1被踢出
     *
     * @mbg.generated Thu Jan 14 10:25:22 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}